<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Camp.Compiler/Camp.Compiler.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="../assets/**/*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
    </Content>
  </ItemGroup>

</Project>
