<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Camp.Compiler/Camp.Compiler.csproj" />
  </ItemGroup>

  <Target Name="CopyCampcToRepoBin" AfterTargets="Build">
    <PropertyGroup>
      <CampcRepoBin>$(MSBuildProjectDirectory)/../../bin/</CampcRepoBin>
    </PropertyGroup>
    <MakeDir Directories="$(CampcRepoBin)" />
    <ItemGroup>
      <CampcRuntimeFiles Include="$(TargetDir)campc*;$(TargetDir)*.dll;$(TargetDir)*.deps.json;$(TargetDir)*.runtimeconfig.json" Exclude="$(TargetDir)*.pdb" />
    </ItemGroup>
    <Copy SourceFiles="@(CampcRuntimeFiles)" DestinationFolder="$(CampcRepoBin)" SkipUnchangedFiles="true" />
  </Target>

</Project>
