<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);VSTHRD200;VSTHRD002;CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OmniSharp.Extensions.DebugAdapter" Version="0.19.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Camp.Compiler/Camp.Compiler.csproj" />
  </ItemGroup>

  <Target Name="CopyCampDapToRepoBin" AfterTargets="Build" Condition="'$(IsPublishingTools)' != 'true'">
    <PropertyGroup>
      <CampDapRepoBin>$(MSBuildProjectDirectory)/../../bin/</CampDapRepoBin>
    </PropertyGroup>
    <MakeDir Directories="$(CampDapRepoBin)" />
    <ItemGroup>
      <CampDapRuntimeFiles Include="$(TargetDir)camp-dap*;$(TargetDir)*.dll;$(TargetDir)*.deps.json;$(TargetDir)*.runtimeconfig.json" Exclude="$(TargetDir)*.pdb" />
    </ItemGroup>
    <Copy SourceFiles="@(CampDapRuntimeFiles)" DestinationFolder="$(CampDapRepoBin)" SkipUnchangedFiles="true" />
  </Target>

</Project>
