[target]
name=c99
include=stdint.h stdbool.h

[define]
C99=1

[declare]
OS_DOS=false
OS_WIN16=false
OS_WIN32=false
OS_WIN64=false
OS_LINUX=false
OS_MACOSX=false
OS_WASI=false
RUNTIME_EMSCRIPTEN=false
SUBSYSTEM_POSIX=false
SUBSYSTEM_DARWIN=false
ARCH_X86=false
ARCH_X64=false
ARCH_ARM64=false
ARCH_WASM32=false
SUPPORTS_FILES=true
SUPPORTS_TIMERS=true
SUPPORTS_THREADS=true
SUPPORTS_NETWORK=true
UNICODE=false

; Reserved for future use.
; SUPPORTS_ENVIRONMENT=true
; SUPPORTS_PROCESSES=true
; SUPPORTS_TERMINAL=true

; Reserved for future use.
; COMPILER_GCC=false
; COMPILER_CLANG=false
; COMPILER_MSVC=false

[declare.callspec]
_cdecl=true
_stdcall=OS_WIN32
_fastcall=OS_WIN32
_thiscall=OS_WIN32
_pascal=OS_WIN16
_winapi=OS_WIN16 || OS_WIN32
_sysv=SUBSYSTEM_POSIX
_msabi=ARCH_X64

[declare.typespec]
_near=OS_WIN16 || OS_WIN32
_far=OS_WIN16 || OS_WIN32
_huge=OS_WIN16 || OS_WIN32

[capability]
c_source_ext=.c

[ctype]
sbyte=int8_t
byte=uint8_t
short=int16_t
ushort=uint16_t
int=int32_t
uint=uint32_t
long=int64_t
ulong=uint64_t
nint=intptr_t
nuint=uintptr_t
float=float
double=double
bool=bool
char=char
achar=char
wchar=uint16_t
uchar=uint32_t

[artifact]
object_ext=.o
exec_prefix=
exec_ext=
static_prefix=lib
static_ext=.a
shared_prefix=lib
shared_ext=.so

[build]
compile={cc} -std=c99 {profile_cflags} {build_cflags} -c {source} -o {object}
exec={cc} {objects} {libs} -o {output} {profile_ldflags}
static={ar} rcs {output} {objects} {libs}
shared={cc} -shared {objects} {libs} -o {output} {profile_ldflags}

[profile.DEBUG]
cflags=-g
ldflags=

[profile.RELEASE]
cflags=-O2
ldflags=
